### ISSUE TITLE
Update to new REST API from Openfire

### ISSUE THREAD

**Issue by Redor** [gidkom/php-openfire-restapi#1]
Could you please update your userservice client which is based on userservice v1 API to userservice v2?
The user service v2 is also build in REST API from openfire. 
See here: http://www.igniterealtime.org/projects/openfire/plugins/restapi/readme.html

**Comment by gidkom** [comment]
Ok, thanks for the info. I will work on that

**Comment by gidkom** [comment]
I have changed form userservice to the REST API

**Comment by Redor** [comment]
Looks great, thy
