### ISSUE TITLE
While using php-openfire-restapi, it has error with dependency of autoload.php

### ISSUE THREAD

**Issue by welkinhawk02** [gidkom/php-openfire-restapi#12]
Hi,

Can you help us resolving the autoload.php dependency error.
We have tried to install with composer, but still couldn't resolve the dependency on autoload.php.

It would be great even if you can share the autoload.php and dependent files on git.

regards,

**Comment by ottoszika** [comment]
Hello,

There were some package name conflicts. Let us know if the problem persists.
Thank you.

Best regards,
Otto Szika
