### ISSUE TITLE
 'cURL error 7: Failed to connect to study.uproom.net port 9090: Connection timed out

### ISSUE THREAD

**Issue by manishkvaish** [gidkom/php-openfire-restapi#16]
I am getting this error, when running my code on shared server
 with no result displaying at all
whereas everything working fine over my laptop local xamp and producing correct results.

Please help me ,what could be the issue?

Thanks

**Comment by gidkom** [comment]
is your openfire working correctly on that address and port?

**Comment by manishkvaish** [comment]
As i told earlier, it is working fine and giving my openfire data
when running the code on my laptop XAMP server as local host

But i have tested it on more than 3 shared server now, it is not giving me anything.
