### ISSUE TITLE
Fix packagist

### ISSUE THREAD

**Issue by fabiomontefuscolo** [gidkom/php-openfire-restapi#28]
Hi!

Your library is on version 1.1.0, but from packagist we can download version 1.0.0 only.

Thank you!

**Comment by marclaporte** [comment]
@gidkom 

Ref: https://packagist.org/packages/gidkom/php-openfire-restapi#1.0.0

Can we help?

Thanks!

**Comment by marclaporte** [comment]
1.1 is from Feb 2018

Perhaps release a new version and try to make it available via Packagist?

Thank you!

**Comment by gidkom** [comment]
ok I'll do that

**Comment by marclaporte** [comment]
> ok I'll do that

It is bot done yet: https://packagist.org/packages/gidkom/php-openfire-restapi
