### ISSUE TITLE
Is there pre-bind future for getting SID, RID for frontend XMPP Clients?

### ISSUE THREAD

**Issue by tural-ali** [gidkom/php-openfire-restapi#5]
What I'm trying to do is, to get RID and SID values for JID in server side. The goal is to keep authenticated Converse JS (frontend client) using it's prebind future. Tried all possible PHP XMPP libraries. Starting from JAXL ending in tiniest libraries like . None of them working.

Is there any possible workaround? How can I write simple connection class to authenticate based on given username and password and get rid, sid? Is it possible using this REST solution?

**Comment by gidkom** [comment]
To authenticate users i recommend using [https://github.com/strophe/strophejs](strophe). 
The RESTAPI only manages the openfire server

**Comment by tural-ali** [comment]
@gidkom  I'm using converse JS. is there any possible way?

**Comment by gidkom** [comment]
I have not worked with converse JS before, but i looking at their docs i think its possible
